- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install aptitude for Ansible
      raw: test -e /usr/bin/aptitude || (apt -y update && apt install -y aptitude)

- hosts: all
  gather_facts: true

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - apt: pkg={{ item }} state=absent purge=yes autoclean=yes
      with_items:
        - webbrowser-app
        - gnome-calendar
        - thunderbird 
        - unity-lens-shopping
    - apt_key: url=https://nvidia.github.io/nvidia-container-runtime/gpgkey state=present
#    - get_url: url=https://nvidia.github.io/nvidia-container-runtime/ubuntu24.04/nvidia-container-runtime.list dest=/etc/apt/sources.list.d/nvidia-container-runtime.list
    - apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
    - apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present
    - apt_key: url=https://updates.signal.org/desktop/apt/keys.asc state=present
#    - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=382E94DE state=present
    - apt_repository: "repo=deb https://download.docker.com/linux/ubuntu noble stable" state=present filename=docker
    - apt_repository: repo={{ item }} state=present
      with_items:
        - ppa:graphics-drivers/ppa
        - ppa:yubico/stable
    - stat: path=/etc/cloud/cloud.cfg
      register: cloud_config
    - lineinfile: 'dest=/etc/cloud/cloud.cfg state=present regexp="^preserve_hostname:" line="preserve_hostname: true"'
      when: cloud_config.stat.exists == True
    - mount: name=swap fstype=swap state=absent
    - command: swapoff -a
      when: ansible_swaptotal_mb > 0
    - apt: update_cache=yes upgrade=yes autoremove=yes
    - package: name={{ item }} state=latest
      with_items:
       - gdebi-core
       - ntp
       - htop
       - iftop
       - bmon
       - apt-transport-https
       - ca-certificates
       - curl
       - libfuse2
       - software-properties-common
       - intel-microcode
       - libpam-u2f
       - traceroute
       - autoconf 
       - build-essential 
       - cmake
       - net-tools
       - docker.io
       - python3-pip
#       - ubuntu-drivers-common
#       - nvidia-container-runtime
       - dkms
       - wireguard
       - nfs-common
       - jq
       - postgresql-client
       - bat
#    - pip: name=docker
    - group: name=sudo state=present
    - group: name=wheel state=present
    - user: name={{ ansible_user }} shell=/bin/bash groups=adm,sudo,wheel,docker,dialout append=yes
    - lineinfile: "dest=/etc/sudoers state=present line='%sudo ALL=(ALL) NOPASSWD: ALL'"
    - sysctl: name=fs.inotify.max_user_watches value=524288
    - sysctl: name=vm.max_map_count value=262144
#    - command: ubuntu-drivers autoinstall
#    - service: name=docker enabled=true 
    - command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
    - command: gdebi --n google-chrome-stable_current_amd64.deb 
    

